In [27]:
import pandas as pd
import numpy as np
from numpy import matmul
from numpy.linalg import inv

"""
e = (yi−^yi)
y = Xw + e
Err=∑(e_i)^2
predicted value of our target: ^y
residual vector : e
"""

# calculating w,y_pred when X,y are given
# x1 = np.array([1, 2, 5])
# x2 = np.array([1, 3, 5])
# x3 = np.array([1, 4, 7])
# X = np.array([np.array([1,_]) for _ in range(1,6)])

x1 = np.array([1,3, 2])
x2 = np.array([1,5, 3])
x3 = np.array([1,6, 4])
x4 = np.array([1,7, 5])
x5 = np.array([1,8, 6])
x6 = np.array([1,9, 7])
X=np.array([x1,x2,x3,x4,x5])

y = np.array([2*_ for _ in range(1,6)])  # y is a vector, so whether its a 1 by 3 or 3 by 1 matrix shouldn't matter much

w = matmul(matmul(inv(matmul(X.T, X)), X.T), y)

# x = np.array([1, 5, 8])

print("X:", X, "y:", y, "w:", w, sep="\n")

X:
[[1 3 2]
 [1 5 3]
 [1 6 4]
 [1 7 5]
 [1 8 6]]
y:
[ 2  4  6  8 10]
w:
[-2.00000000e+00  1.59872116e-14  2.00000000e+00]
